# Welcome to Jekyll!
#

# Site settings
title: NISHANT GUPTA
description: |
  A PORTFOLIO AND RESUME
owner: Nishant Gupta # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: im.nishantg@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://imnishantg.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/imnishantg
  github: https://github.com/imnishantg
  linkedin-square: https://www.linkedin.com/in/imnishantg/
  facebook-official: https://facebook.com/imnishantg
  # google-plus-square: https://plus.google.com/u/0/+<username>
  email: im.nishantg@gmail.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
